import React, { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, ShieldCheck, Loader2 } from 'lucide-react';
import { api } from '../../lib/supabase';
import { legalKeys } from '../../features/legal/keys';
import { LegalEnvironment } from '../../types';

export const sbzStatusKey = ['legal_sbz_status'];
export function useSbzStatus() { return useQuery({queryKey:sbzStatusKey,queryFn:()=>api.callSbz('/sbz/status'),retry:false}); }

export default function SbzSettings({ environment, onEnvironmentChange }: {
  environment: LegalEnvironment;
  onEnvironmentChange: (environment: LegalEnvironment) => void;
}) {
  const {data:status,error}=useSbzStatus();const cache=useQueryClient();
  const [key,setKey]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(() => { setKey(''); setMessage(''); }, [environment]);
  const [checks,setChecks]=useState<Record<string,boolean>>({});
  const run=async(fn:()=>Promise<unknown>,success:string)=>{setBusy(true);setMessage('');try{await fn();setMessage(success);await cache.invalidateQueries({queryKey:sbzStatusKey});}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  return <section className="rounded-2xl border border-emerald-200 bg-gradient-to-br from-emerald-50 to-white p-5 space-y-5">
    <div className="flex items-start gap-3"><ShieldCheck className="text-emerald-700"/><div><h2 className="font-black text-slate-900">Ηλεκτρονική τιμολόγηση · SBZ</h2><p className="mt-1 text-sm text-slate-600">Τα παραστατικά αποστέλλονται αποκλειστικά στον πάροχο. Οι δοκιμές έχουν ανεξάρτητο αρχείο και αρίθμηση.</p></div></div>
    <div className="grid sm:grid-cols-2 gap-3">{(['dev','prod'] as const).map(e=><div key={e} className="rounded-xl bg-white border border-slate-200 p-4"><p className="font-bold">{e==='dev'?'Δοκιμαστικό περιβάλλον':'Πραγματικά παραστατικά'}</p><p className="mt-2 text-sm flex items-center gap-2"><CheckCircle2 size={16} className={status?.[e]?.ready?'text-emerald-600':'text-slate-400'}/>{status?.[e]?.ready?'Διαθέσιμο για έκδοση':status?.[e]?.configured?'Η σύνδεση έχει ρυθμιστεί · αναμένει ενεργοποίηση':'Αναμένει στοιχεία σύνδεσης'}</p></div>)}</div>
    <div className="grid gap-3 sm:grid-cols-[1fr_2fr_auto] items-end"><label className="text-sm font-bold">Περιβάλλον σύνδεσης<select disabled={busy} value={environment} onChange={e=>onEnvironmentChange(e.target.value as LegalEnvironment)} className="mt-1 block w-full rounded-lg border p-2"><option value="dev">Δοκιμές</option><option value="prod">Παραγωγή</option></select></label><label className="text-sm font-bold">Κλειδί σύνδεσης SBZ<input disabled={busy} type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)} className="mt-1 block w-full rounded-lg border p-2"/></label><button disabled={busy||!key.trim()} onClick={()=>void run(async()=>{await api.callSbz('/sbz/configure',{environment,apiKey:key});setKey('');await cache.invalidateQueries({queryKey:legalKeys.settings()});},`Η σύνδεση αποθηκεύτηκε στο περιβάλλον «${environment==='dev'?'Δοκιμές':'Παραγωγή'}». Ελέγξτε την παρακάτω.`)} className="rounded-lg bg-emerald-700 px-4 py-2 text-white font-bold disabled:opacity-50">Αποθήκευση</button></div>
    <button disabled={busy} onClick={()=>void run(()=>api.callSbz('/sbz/check',{environment}),'Η σύνδεση με την SBZ επαληθεύτηκε.')} className="text-sm font-bold text-emerald-800 underline">Έλεγχος σύνδεσης</button>
    {status?.unresolved?.length > 0 && <details className="rounded-xl border border-amber-200 bg-amber-50 p-4"><summary className="font-bold cursor-pointer">Παλιά παραστατικά που χρειάζονται έλεγχο ({status.unresolved.length})</summary><p className="text-sm my-3">Επιβεβαιώστε από το αρχικό αρχείο αν πρόκειται για δοκιμή ή πραγματικό παραστατικό. Η επιλογή καταγράφεται στο ιστορικό.</p>{status.unresolved.map((d:any)=><div key={d.id} className="flex flex-wrap items-center gap-2 border-t py-2 text-sm"><span className="mr-auto">{d.series}–{d.aa} · {d.issue_date}</span>{['dev','prod'].map(e=><button key={e} disabled={busy} onClick={()=>void run(()=>api.callSbz('/sbz/legacy-environment',{documentId:d.id,environment:e}),'Το περιβάλλον επιβεβαιώθηκε.')} className="rounded border bg-white px-3 py-1">{e==='dev'?'Ήταν δοκιμή':'Ήταν πραγματικό'}</button>)}</div>)}</details>}
    <details className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer font-bold">{status?.productionEnabled?'Διαχείριση παραγωγικής λειτουργίας':'Προετοιμασία για πραγματικά παραστατικά'}</summary><p className="text-sm text-slate-600 my-3">Η ενεργοποίηση απαιτεί επιτυχή δοκιμή και ολοκλήρωση των παρακάτω ελέγχων.</p><div className="space-y-3">{Object.entries({sbz_approved:'Η SBZ ενέκρινε τη διασύνδεση και ενεργοποίησε τον λογαριασμό.',numbering_reviewed:'Ελέγχθηκαν οι σειρές και τα παλιά παραστατικά.',backup_completed:'Δημιουργήθηκε και ελέγχθηκε αντίγραφο ασφαλείας.',delivery_confirmed:'Επιβεβαιώθηκε με την SBZ η κάλυψη των απαιτούμενων διαδικασιών διακίνησης.'}).map(([id,label])=><label key={id} className="flex gap-2 text-sm"><input type="checkbox" checked={!!checks[id]} onChange={e=>setChecks(c=>({...c,[id]:e.target.checked}))}/>{label}</label>)}</div><button disabled={busy||(!status?.productionEnabled&&Object.values(checks).filter(Boolean).length!==4)} onClick={()=>void run(()=>api.callSbz('/sbz/activate',{enabled:!status?.productionEnabled,checks}),status?.productionEnabled?'Η νέα παραγωγική έκδοση έχει παύσει.':'Η παραγωγική έκδοση ενεργοποιήθηκε.')} className="mt-4 rounded-lg bg-slate-900 px-4 py-2 text-white font-bold disabled:opacity-40">{status?.productionEnabled?'Παύση νέας έκδοσης':'Ενεργοποίηση παραγωγής'}</button></details>
    {(message||error)&&<p role="status" className="rounded-lg bg-white border p-3 text-sm">{message||(error as Error)?.message}</p>}{busy&&<Loader2 className="animate-spin" aria-label="Εκτελείται έλεγχος"/>}
  </section>;
}
