export type AdminPage =
  | 'dashboard'
  | 'registry'
  | 'inventory'
  | 'pricing'
  | 'settings'
  | 'resources'
  | 'collections'
  | 'batch-print'
  | 'orders'
  | 'production'
  | 'consignments'
  | 'repairs'
  | 'customers'
  | 'suppliers'
  | 'sellers'
  | 'ai-studio'
  | 'pricelist'
  | 'analytics'
  | 'offers'
  | 'deliveries'
  | 'legal';

export type MobileAdminPage =
  | 'dashboard'
  | 'orders'
  | 'order-builder'
  | 'deliveries'
  | 'production'
  | 'consignments'
  | 'repairs'
  | 'inventory'
  | 'menu'
  | 'registry'
  | 'ai-studio'
  | 'settings'
  | 'resources'
  | 'customers'
  | 'suppliers'
  | 'sellers'
  | 'pricing'
  | 'batch-print'
  | 'collections'
  | 'pricelist'
  | 'offers'
  | 'analytics'
  | 'legal';

export type EmployeePage =
  | 'dashboard'
  | 'orders'
  | 'deliveries'
  | 'production'
  | 'consignments'
  | 'repairs'
  | 'registry'
  | 'customers'
  | 'collections'
  | 'inventory';

export type SellerPage =
  | 'dashboard'
  | 'catalog'
  | 'collections'
  | 'orders'
  | 'customers'
  | 'consignments'
  | 'repairs'
  | 'order-builder';
